const express=require('express');
const path=require('path');
const fs=require('fs');
const crypto=require('crypto');
const bcrypt=require('bcrypt');
const multer=require('multer');
const helmet=require('helmet');
const rateLimit=require('express-rate-limit');
const {Pool}=require('pg');

const app=express();
const PORT=Number(process.env.PORT||3000);
const UPLOAD_DIR=path.resolve(process.env.UPLOAD_DIR||'./uploads');
const MAX_UPLOAD_MB=Number(process.env.MAX_UPLOAD_MB||200);
const SESSION_DAYS=Number(process.env.SESSION_DAYS||30);
const WORKSHOP_PUBLIC_URL=(process.env.WORKSHOP_PUBLIC_URL||'https://hl2sbpp-worckshop-v1.onrender.com').replace(/\/+$/,'');
if(!process.env.DATABASE_URL){console.error('DATABASE_URL is missing.');process.exit(1)}
fs.mkdirSync(UPLOAD_DIR,{recursive:true});
const pool=new Pool({connectionString:process.env.DATABASE_URL});
if(process.env.NODE_ENV==='production') app.set('trust proxy',1);
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));
app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:false}));
app.use(express.static(path.join(__dirname,'public')));
app.use('/uploads',express.static(UPLOAD_DIR,{maxAge:'1d'}));
const authLimiter=rateLimit({windowMs:15*60*1000,limit:40,standardHeaders:true,legacyHeaders:false});
const storage=multer.diskStorage({destination:(_q,_f,cb)=>cb(null,UPLOAD_DIR),filename:(_q,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase();cb(null,`${Date.now()}-${crypto.randomBytes(8).toString('hex')}${ext}`)}});
const upload=multer({storage,limits:{fileSize:MAX_UPLOAD_MB*1024*1024},fileFilter:(_q,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase();if(file.fieldname==='package')return cb(null,ext==='.zip');cb(null,['.png','.jpg','.jpeg','.webp','.gif'].includes(ext))}});
const avatarUpload=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(_q,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase();cb(null,['.png','.jpg','.jpeg','.webp','.gif'].includes(ext))}});
function cleanText(v,max){return String(v??'').trim().slice(0,max)}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
function getSid(req){return req.headers.cookie?.match(/(?:^|;\s*)hl2sbpp_session=([^;]+)/)?.[1]||null}
function setSid(res,id,maxAge){const secure=process.env.NODE_ENV==='production'?'; Secure':'';res.setHeader('Set-Cookie',`hl2sbpp_session=${id}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${maxAge}${secure}`)}
function localUrl(req,filename){return `${process.env.PUBLIC_URL?.replace(/\/+$/,'')||`${req.protocol}://${req.get('host')}`}/uploads/${encodeURIComponent(filename)}`}
function oldUrl(v){if(!v)return v;if(/^https?:\/\//i.test(v))return v;if(v.startsWith('/uploads/'))return WORKSHOP_PUBLIC_URL+v;return v}
function safeUnlink(f){if(!f)return;try{const p=path.join(UPLOAD_DIR,path.basename(f));if(fs.existsSync(p))fs.unlinkSync(p)}catch{}}
async function createSession(uid){const id=crypto.randomBytes(32).toString('hex');const exp=new Date(Date.now()+SESSION_DAYS*86400000);await pool.query('INSERT INTO sessions(id,user_id,expires_at) VALUES($1,$2,$3)',[id,uid,exp]);return id}
async function auth(req,res,next){try{const sid=getSid(req);if(!sid)return res.status(401).json({error:'Authentication required'});const r=await pool.query(`SELECT u.id,u.username,u.email,u.role,u.avatar_url,u.bio,u.theme_color,u.theme_mode,u.banned FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=$1 AND s.expires_at>NOW()`,[sid]);if(!r.rowCount)return res.status(401).json({error:'Session expired'});if(r.rows[0].banned)return res.status(403).json({error:'Account is banned'});req.user=r.rows[0];req.sessionId=sid;next()}catch(e){console.error(e);res.status(500).json({error:'Authentication check failed'})}}
async function initDb(){try{const schema=fs.readFileSync(path.join(__dirname,'db','schema.sql'),'utf8');await pool.query(schema)}catch(e){console.error('DB schema init failed',e)}}

app.get('/addon/:id',(req,res)=>/^\d+$/.test(req.params.id)?res.sendFile(path.join(__dirname,'public','addon.html')):res.redirect('/'));
app.get('/api/health',async(_q,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,database:'supabase-postgres'})}catch{res.status(503).json({ok:false,database:'unavailable'})}});
app.get('/api/me',async(req,res)=>{try{const sid=getSid(req);if(!sid)return res.json({user:null});const r=await pool.query(`SELECT u.id,u.username,u.email,u.role,u.avatar_url,u.bio,u.theme_color,u.theme_mode,u.banned FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=$1 AND s.expires_at>NOW()`,[sid]);res.json({user:r.rowCount&&!r.rows[0].banned?r.rows[0]:null})}catch{res.json({user:null})}});
app.post('/api/register',authLimiter,async(req,res)=>{try{const username=cleanText(req.body.username,32),email=cleanText(req.body.email,255).toLowerCase(),password=String(req.body.password||''),repeat=String(req.body.repeatPassword||'');if(!/^[a-zA-Z0-9_.-]{3,32}$/.test(username))return res.status(400).json({error:'Username: 3-32 characters, letters/numbers/._-'});if(!validEmail(email))return res.status(400).json({error:'Invalid email'});if(password.length<8)return res.status(400).json({error:'Password must be at least 8 characters'});if(password!==repeat)return res.status(400).json({error:'Passwords do not match'});const hash=await bcrypt.hash(password,12);let r;try{r=await pool.query(`INSERT INTO users(username,email,password_hash) VALUES($1,$2,$3) RETURNING id,username,email,role,avatar_url,bio,theme_color,theme_mode,banned`,[username,email,hash])}catch(e){if(e?.code==='23505')return res.status(409).json({error:'Email or username already exists'});throw e}const sid=await createSession(r.rows[0].id);setSid(res,sid,SESSION_DAYS*86400);res.json({user:r.rows[0]})}catch(e){console.error(e);res.status(500).json({error:'Registration failed'})}});
app.post('/api/login',authLimiter,async(req,res)=>{try{const email=cleanText(req.body.email,255).toLowerCase(),password=String(req.body.password||'');const r=await pool.query(`SELECT id,username,email,password_hash,role,avatar_url,bio,theme_color,theme_mode,banned FROM users WHERE lower(email)=lower($1)`,[email]);if(!r.rowCount||!(await bcrypt.compare(password,r.rows[0].password_hash)))return res.status(401).json({error:'Wrong email or password'});if(r.rows[0].banned)return res.status(403).json({error:'Account is banned'});const u=r.rows[0],sid=await createSession(u.id);setSid(res,sid,SESSION_DAYS*86400);res.json({user:u})}catch(e){console.error(e);res.status(500).json({error:'Login failed'})}});
app.post('/api/logout',async(req,res)=>{try{const sid=getSid(req);if(sid)await pool.query('DELETE FROM sessions WHERE id=$1',[sid])}finally{setSid(res,'',0);res.json({ok:true})}});
app.get('/api/addons',async(req,res)=>{try{const q=cleanText(req.query.q,100),category=cleanText(req.query.category,30),sort=cleanText(req.query.sort,20),p=[],w=[];if(q){p.push(`%${q}%`);w.push(`(a.title ILIKE $${p.length} OR a.description ILIKE $${p.length} OR u.username ILIKE $${p.length})`)}if(category&&category!=='All'){p.push(category);w.push(`a.category=$${p.length}`)}let order='a.created_at DESC';if(sort==='popular'||sort==='rating')order='a.likes DESC,a.downloads DESC,a.created_at DESC';if(sort==='downloads')order='a.downloads DESC,a.created_at DESC';const r=await pool.query(`SELECT a.id,a.title,a.description,a.category,a.version,a.downloads,a.likes,a.created_at,a.file_size,a.cover_image,u.username AS author,u.avatar_url AS author_avatar,u.role AS author_role FROM addons a JOIN users u ON u.id=a.user_id ${w.length?'WHERE '+w.join(' AND '):''} ORDER BY ${order} LIMIT 100`,p);res.json({addons:r.rows.map(a=>({...a,cover_image:oldUrl(a.cover_image),author_avatar:oldUrl(a.author_avatar)}))})}catch(e){console.error(e);res.status(500).json({error:'Failed to load addons'})}});
app.get('/api/addons/:id',async(req,res)=>{try{const r=await pool.query(`SELECT a.id,a.title,a.description,a.category,a.version,a.downloads,a.likes,a.created_at,a.file_size,a.original_filename,a.cover_image,u.id AS author_id,u.username AS author,u.avatar_url AS author_avatar,u.role AS author_role FROM addons a JOIN users u ON u.id=a.user_id WHERE a.id=$1`,[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Addon not found'});const images=await pool.query('SELECT id,image_url FROM addon_images WHERE addon_id=$1 ORDER BY id',[req.params.id]);const comments=await pool.query(`SELECT c.id,c.body,c.created_at,u.id AS user_id,u.username,u.avatar_url,u.role FROM comments c JOIN users u ON u.id=c.user_id WHERE c.addon_id=$1 ORDER BY c.created_at DESC`,[req.params.id]);const a=r.rows[0];res.json({addon:{...a,cover_image:oldUrl(a.cover_image),author_avatar:oldUrl(a.author_avatar)},images:images.rows.map(x=>({...x,image_url:oldUrl(x.image_url)})),comments:comments.rows.map(x=>({...x,avatar_url:oldUrl(x.avatar_url)}))})}catch(e){console.error(e);res.status(500).json({error:'Failed to load addon'})}});
app.post('/api/addons',auth,upload.fields([{name:'package',maxCount:1},{name:'cover',maxCount:1},{name:'gallery',maxCount:6}]),async(req,res)=>{try{const pkg=req.files?.package?.[0];if(!pkg)return res.status(400).json({error:'ZIP package required'});const title=cleanText(req.body.title,100),description=cleanText(req.body.description,5000),category=cleanText(req.body.category,30)||'Other',version=cleanText(req.body.version,30)||'1.0.0';if(title.length<2){safeUnlink(pkg.filename);(req.files.cover||[]).forEach(f=>safeUnlink(f.filename));(req.files.gallery||[]).forEach(f=>safeUnlink(f.filename));return res.status(400).json({error:'Title is required'})}const cover=req.files?.cover?.[0]?localUrl(req,req.files.cover[0].filename):null;const r=await pool.query(`INSERT INTO addons(user_id,title,description,category,version,filename,original_filename,file_size,cover_image) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,title,description,category,version,downloads,likes,file_size,cover_image`,[req.user.id,title,description,category,version,pkg.filename,pkg.originalname,pkg.size,cover]);const id=r.rows[0].id;for(const f of(req.files?.gallery||[]))await pool.query('INSERT INTO addon_images(addon_id,image_url) VALUES($1,$2)',[id,localUrl(req,f.filename)]);res.status(201).json({addon:r.rows[0]})}catch(e){console.error(e);for(const key of ['package','cover','gallery'])(req.files?.[key]||[]).forEach(f=>safeUnlink(f.filename));res.status(500).json({error:'Upload failed'})}});
app.get('/api/addons/:id/download',async(req,res)=>{try{const r=await pool.query('SELECT filename,original_filename FROM addons WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Addon not found'});const file=path.join(UPLOAD_DIR,r.rows[0].filename);if(fs.existsSync(file)){await pool.query('UPDATE addons SET downloads=downloads+1 WHERE id=$1',[req.params.id]);return res.download(file,r.rows[0].original_filename)}const target=WORKSHOP_PUBLIC_URL+'/api/addons/'+encodeURIComponent(req.params.id)+'/download';res.redirect(307,target)}catch(e){console.error(e);res.status(500).json({error:'Download failed'})}});
app.post('/api/addons/:id/like',auth,async(req,res)=>{const c=await pool.connect();try{await c.query('BEGIN');const old=await c.query('SELECT 1 FROM addon_likes WHERE addon_id=$1 AND user_id=$2',[req.params.id,req.user.id]);if(old.rowCount){await c.query('DELETE FROM addon_likes WHERE addon_id=$1 AND user_id=$2',[req.params.id,req.user.id]);await c.query('UPDATE addons SET likes=GREATEST(likes-1,0) WHERE id=$1',[req.params.id])}else{await c.query('INSERT INTO addon_likes(addon_id,user_id) VALUES($1,$2)',[req.params.id,req.user.id]);await c.query('UPDATE addons SET likes=likes+1 WHERE id=$1',[req.params.id])}await c.query('COMMIT');const r=await pool.query('SELECT likes FROM addons WHERE id=$1',[req.params.id]);res.json({likes:r.rows[0]?.likes??0})}catch(e){await c.query('ROLLBACK');res.status(500).json({error:'Like failed'})}finally{c.release()}});
app.post('/api/addons/:id/comments',auth,async(req,res)=>{const body=cleanText(req.body.body,1000);if(!body)return res.status(400).json({error:'Comment is empty'});const r=await pool.query('INSERT INTO comments(addon_id,user_id,body) VALUES($1,$2,$3) RETURNING id,body,created_at',[req.params.id,req.user.id,body]);res.status(201).json({comment:r.rows[0]})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
initDb().then(()=>app.listen(PORT,()=>console.log(`HL2SBPP Addons direct DB running on port ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
