const express=require('express');
const path=require('path');const crypto=require('crypto');const bcrypt=require('bcrypt');const helmet=require('helmet');const rateLimit=require('express-rate-limit');const multer=require('multer');const {Pool}=require('pg');
const app=express();const PORT=Number(process.env.PORT||3000);const OLD=(process.env.WORKSHOP_API_URL||'https://hl2sbpp-worckshop.onrender.com').replace(/\/$/,'');const SESSION_DAYS=30;
if(!process.env.DATABASE_URL) throw new Error('DATABASE_URL is missing');
const pool=new Pool({connectionString:process.env.DATABASE_URL});app.set('trust proxy',1);app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:false}));app.use(express.static(path.join(__dirname,'public')));
const limiter=rateLimit({windowMs:15*60*1000,limit:40,standardHeaders:true,legacyHeaders:false});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:Number(process.env.MAX_UPLOAD_MB||200)*1024*1024}});
const schema=`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,username VARCHAR(32) NOT NULL UNIQUE,email VARCHAR(255) NOT NULL UNIQUE,password_hash TEXT NOT NULL,role VARCHAR(20) NOT NULL DEFAULT 'user',banned BOOLEAN NOT NULL DEFAULT FALSE,avatar_url TEXT,bio VARCHAR(500) NOT NULL DEFAULT '',theme_color VARCHAR(20) NOT NULL DEFAULT '#159cff',theme_mode VARCHAR(10) NOT NULL DEFAULT 'dark',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE users ADD COLUMN IF NOT EXISTS banned BOOLEAN NOT NULL DEFAULT FALSE; ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT; ALTER TABLE users ADD COLUMN IF NOT EXISTS bio VARCHAR(500) NOT NULL DEFAULT ''; ALTER TABLE users ADD COLUMN IF NOT EXISTS theme_color VARCHAR(20) NOT NULL DEFAULT '#159cff'; ALTER TABLE users ADD COLUMN IF NOT EXISTS theme_mode VARCHAR(10) NOT NULL DEFAULT 'dark';
CREATE TABLE IF NOT EXISTS sessions(id CHAR(64) PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL);`;
async function init(){await pool.query(schema)}
function cookie(req){return req.headers.cookie?.match(/(?:^|;\s*)hl2sbpp_session=([^;]+)/)?.[1]||null}function setCookie(res,v,max){res.setHeader('Set-Cookie',`hl2sbpp_session=${v}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${max}${process.env.NODE_ENV==='production'?'; Secure':''}`)}
async function session(userId){const id=crypto.randomBytes(32).toString('hex');const exp=new Date(Date.now()+SESSION_DAYS*864e5);await pool.query('INSERT INTO sessions(id,user_id,expires_at) VALUES($1,$2,$3)',[id,userId,exp]);return id}
async function userFor(req){const sid=cookie(req);if(!sid)return null;const r=await pool.query(`SELECT u.id,u.username,u.email,u.role,u.avatar_url,u.bio,u.theme_color,u.theme_mode,u.banned FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=$1 AND s.expires_at>NOW()`,[sid]);return r.rowCount&&!r.rows[0].banned?r.rows[0]:null}
async function auth(req,res,next){const u=await userFor(req);if(!u)return res.status(401).json({error:'Authentication required'});req.user=u;next()}
function clean(v,n){return String(v??'').trim().slice(0,n)}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
async function proxy(req,res,method,pathName,body,headers={}){try{const h={...headers};const sid=cookie(req);if(sid)h.cookie=`hl2sbpp_session=${sid}`;if(body && !(body instanceof FormData)){h['content-type']='application/json'}const r=await fetch(OLD+pathName,{method,headers:h,body:body instanceof FormData?body:(body?JSON.stringify(body):undefined),redirect:'manual'});const ct=r.headers.get('content-type')||'';res.status(r.status);if(ct.includes('application/json'))res.json(await r.json());else{res.set('content-type',ct);res.send(Buffer.from(await r.arrayBuffer()))}}catch(e){console.error(e);res.status(502).json({error:'Workshop server unavailable'})}}
app.get('/addon/:id',(req,res)=>/^\d+$/.test(req.params.id)?res.sendFile(path.join(__dirname,'public','addon.html')):res.redirect('/'));
app.get('/api/health',async(_q,res)=>{try{await pool.query('SELECT 1');res.json({ok:true})}catch{res.status(503).json({ok:false})}});
app.get('/api/me',async(req,res)=>res.json({user:await userFor(req)}));
app.post('/api/register',limiter,async(req,res)=>{try{const username=clean(req.body.username,32),email=clean(req.body.email,255).toLowerCase(),password=String(req.body.password||''),repeat=String(req.body.repeatPassword||'');if(!/^[a-zA-Z0-9_.-]{3,32}$/.test(username))return res.status(400).json({error:'Username: 3-32 characters'});if(!validEmail(email))return res.status(400).json({error:'Invalid email'});if(password.length<8||password!==repeat)return res.status(400).json({error:password.length<8?'Password must be at least 8 characters':'Passwords do not match'});const x=await pool.query('SELECT 1 FROM users WHERE lower(email)=lower($1) OR lower(username)=lower($2)',[email,username]);if(x.rowCount)return res.status(409).json({error:'Email or username already exists'});const hash=await bcrypt.hash(password,12);const r=await pool.query('INSERT INTO users(username,email,password_hash) VALUES($1,$2,$3) RETURNING id,username,email,role,avatar_url,bio,theme_color,theme_mode,banned',[username,email,hash]);setCookie(res,await session(r.rows[0].id, ),SESSION_DAYS*86400);res.json({user:r.rows[0]})}catch(e){console.error(e);res.status(500).json({error:'Registration failed'})}});
app.post('/api/login',limiter,async(req,res)=>{try{const email=clean(req.body.email,255).toLowerCase(),password=String(req.body.password||'');const r=await pool.query('SELECT id,username,email,password_hash,role,avatar_url,bio,theme_color,theme_mode,banned FROM users WHERE lower(email)=lower($1)',[email]);if(!r.rowCount||!(await bcrypt.compare(password,r.rows[0].password_hash)))return res.status(401).json({error:'Wrong email or password'});if(r.rows[0].banned)return res.status(403).json({error:'Account is banned'});const u=r.rows[0];setCookie(res,await session(u.id),SESSION_DAYS*86400);delete u.password_hash;res.json({user:u})}catch(e){console.error(e);res.status(500).json({error:'Login failed'})}});
app.post('/api/logout',async(req,res)=>{const sid=cookie(req);if(sid)await pool.query('DELETE FROM sessions WHERE id=$1',[sid]);setCookie(res,'',0);res.json({ok:true})});
app.get('/api/addons',(req,res)=>proxy(req,res,'GET','/api/addons'+(req.url.includes('?')?req.url.slice(req.url.indexOf('?')):'')));
app.get('/api/addons/:id',(req,res)=>proxy(req,res,'GET',`/api/addons/${encodeURIComponent(req.params.id)}`));
app.get('/api/addons/:id/download',(req,res)=>res.redirect(OLD+`/api/addons/${encodeURIComponent(req.params.id)}/download`));
app.post('/api/addons/:id/like',auth,(req,res)=>proxy(req,res,'POST',`/api/addons/${req.params.id}/like`,{}));
app.post('/api/addons/:id/subscribe',auth,(req,res)=>proxy(req,res,'POST',`/api/addons/${req.params.id}/subscribe`,{}));
app.post('/api/addons/:id/comments',auth,(req,res)=>proxy(req,res,'POST',`/api/addons/${req.params.id}/comments`,{body:clean(req.body.body,1000)}));
app.post('/api/addons',auth,upload.fields([{name:'package',maxCount:1},{name:'cover',maxCount:1},{name:'gallery',maxCount:6}]),async(req,res)=>{try{const form=new FormData();for(const k of ['title','description','category','version'])form.append(k,clean(req.body[k],k==='description'?5000:100));for(const k of ['package','cover']){const f=req.files?.[k]?.[0];if(f)form.append(k,new Blob([f.buffer],{type:f.mimetype}),f.originalname)}for(const f of (req.files?.gallery||[]))form.append('gallery',new Blob([f.buffer],{type:f.mimetype}),f.originalname);await proxy(req,res,'POST','/api/addons',form)}catch(e){console.error(e);res.status(500).json({error:'Upload failed'})}});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
init().then(()=>app.listen(PORT,()=>console.log('HL2SBPP Addons listening on '+PORT))).catch(e=>{console.error(e);process.exit(1)});